Add script dl links and some minor fixes

diff --git a/downloads/vmctl b/downloads/vmctl
--- a/downloads/vmctl
+++ b/downloads/vmctl
@@ -1,7 +1,9 @@
 #!/bin/bash
 # Description:
 # Tool to easily control VM's from the CLI
-# Written by: André Hansen - Andr0id88 on github.
+# Written by: André Hansen
+# Github: https://github.com/Andr0id88
+#License: MIT License
 
 # Color variables
 reset=$'\e[0m'
@@ -11,6 +13,32 @@ red=$'\e[1;31m'
 
 # Catch SIGINT (Ctrl+C) and exit gracefully
 trap 'echo -e "\nProgram terminated by user."; exit' SIGINT
+
+# Check for fzf and offer to install if not found
+if ! command -v fzf &> /dev/null; then
+    echo "${yellow}fzf could not be found.${reset}"
+
+    # Default to Yes if the user presses enter without giving an answer:
+    read -r -p "Would you like to install fzf? [Y/n] " response
+    response=${response:-Y}  # Default value is Y
+    if [[ "$response" =~ ^([yY][eE][sS]|[yY])$ ]]
+    then
+        echo "${yellow}Attempting to install fzf...${reset}"
+
+        # Git clone and install fzf
+        git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf
+        ~/.fzf/install
+
+        # After installation, you may want to check if fzf is available
+        if ! command -v fzf &> /dev/null; then
+            echo "${red}Installation failed. Please install fzf manually.${reset}"
+            exit 1
+        fi
+    else
+        echo "${red}Installation cancelled. fzf is required to run this script.${reset}"
+        exit 1
+    fi
+fi
 
 main_menu() {
   choice=$(printf "Start VM\nStop VM\nTake Snapshot\nRevert to Snapshot\nDelete Snapshot\nList Snapshots\nExit\n" | fzf --prompt="Select an action> " --height=40% --layout=reverse) || exit
@@ -26,21 +54,6 @@ main_menu() {
     *) echo "Invalid option or action cancelled."; main_menu ;;
   esac
 }
-#
-#
-#main_menu() {
-#  choice=$(printf "Start VM\nStop VM\nTake Snapshot\nRevert to Snapshot\nDelete Snapshot\nExit\n" | fzf --prompt="Select an action> " --height=40% --layout=reverse) || exit
-#
-#  case $choice in
-#    "Start VM") start_vm ;;
-#    "Stop VM") stop_vm ;;
-#    "Take Snapshot") take_snapshot ;;
-#    "Revert to Snapshot") revert_snapshot ;;
-#    "Delete Snapshot") delete_snapshot ;;
-#    "Exit") clean_exit ;;
-#    *) echo "Invalid option or action cancelled."; main_menu ;;
-#  esac
-#}
 
 start_vm() {
   # Get all VMs
@@ -67,11 +80,11 @@ start_vm() {
 
   if [ -z "$selected_vms" ]; then
     echo -e "${yellow}Action cancelled.${reset}"
-    main_menu # Return to main menu if action is cancelled
+    main_menu
     return
   fi
 
-  clear # Clear the screen before showing the VM start output
+  clear
   for vm in $selected_vms; do
     echo -e "${yellow}Waiting for VM \"$vm\" to power on...${reset}"
     if VBoxManage startvm "$vm" --type headless >/dev/null; then
@@ -80,54 +93,9 @@ start_vm() {
       echo -e "${red}Failed to start VM \"$vm\".${reset}"
     fi
   done
-  echo # Add a newline for spacing
-  main_menu # Return to main menu after starting VMs
+  echo
+  main_menu
 }
-
-
-
-#start_vm() {
-#  # Get all VMs
-#  mapfile -t all_vms < <(VBoxManage list vms | cut -d '"' -f2)
-#
-#  # Get running VMs
-#  mapfile -t running_vms < <(VBoxManage list runningvms | cut -d '"' -f2)
-#
-#  # Filter out running VMs to get only the powered off VMs
-#  powered_off_vms=()
-#  for vm in "${all_vms[@]}"; do
-#    if [[ ! " ${running_vms[*]} " =~ " $vm " ]]; then
-#      powered_off_vms+=("$vm")
-#    fi
-#  done
-#
-#  if [ ${#powered_off_vms[@]} -eq 0 ]; then
-#    echo "All VMs are currently running."
-#    main_menu
-#    return
-#  fi
-#
-#  selected_vms=$(printf "%s\n" "${powered_off_vms[@]}" | fzf --prompt="Start VM(s)> " --height=40% --layout=reverse -m)
-#
-#  if [ -z "$selected_vms" ]; then
-#    echo "Action cancelled."
-#    main_menu # Return to main menu if action is cancelled
-#    return
-#  fi
-#
-#  clear # Clear the screen before showing the VM start output
-#  for vm in $selected_vms; do
-#  echo -e "${yellow}Waiting for VM \"$vm\" to power on...${reset}"
-#  VBoxManage startvm "$vm" --type headless >/dev/null
-#  if [ $? -eq 0 ]; then
-#      echo -e "${green}VM \"$vm\" has been successfully started.${reset}"
-#  else
-#      echo -e "${red}Failed to start VM \"$vm\".${reset}"
-#  fi
-#done
-#  echo # Add a newline for spacing
-#  main_menu # Return to main menu after starting VMs
-#}
 
 stop_vm() {
   # Fetch only running VMs
@@ -152,45 +120,20 @@ stop_vm() {
   done <<< "$selected_vms"
   main_menu
 }
-#
-#
-#stop_vm() {
-#  # Fetch only running VMs
-#  mapfile -t running_vms < <(VBoxManage list runningvms | cut -d '"' -f2)
-#  if [ ${#running_vms[@]} -eq 0 ]; then
-#    echo -e "${red}No running VMs found.${reset}"
-#    main_menu
-#    return
-#  fi
-#
-#  selected_vms=$(printf "%s\n" "${running_vms[@]}" | fzf --prompt="Stop VM(s)> " --height=40% --layout=reverse -m)
-#
-#  if [ -z "$selected_vms" ]; then
-#    echo -e "${yellow}Action cancelled.${reset}"
-#    main_menu
-#    return
-#  fi
-#
-#  while IFS= read -r vm; do
-#    VBoxManage controlvm "$vm" poweroff
-#    echo -e "${green}$vm stopped.${reset}"
-#  done <<< "$selected_vms"
-#  main_menu
-#}
 
 take_snapshot() {
   mapfile -t my_vms < <(VBoxManage list vms | cut -d '"' -f2)
   vm=$(printf "%s\n" "${my_vms[@]}" | fzf --prompt="Snapshot> " --height=40% --layout=reverse)
 
   if [ -z "$vm" ]; then
-    echo -e "${red}Action cancelled.${reset}"  # Ensure correct color variable usage
+    echo -e "${red}Action cancelled.${reset}"
     main_menu
     return
   fi
 
   read -rp "Enter snapshot name: " snap_name
-  VBoxManage snapshot "$vm" take "$snap_name" >/dev/null 2>&1  # Suppress command output
-  echo -e "${green}Snapshot '$snap_name' taken for $vm.${reset}"  # Use color for success message
+  VBoxManage snapshot "$vm" take "$snap_name" >/dev/null 2>&1
+  echo -e "${green}Snapshot '$snap_name' taken for $vm.${reset}"
   main_menu
 }
 
@@ -205,14 +148,14 @@ delete_snapshot() {
   done < <(VBoxManage list vms)
 
   if [ ${#vms_with_snapshots[@]} -eq 0 ]; then
-    echo -e "${red}No VMs with snapshots found.${reset}"  # Correct color variable usage
+    echo -e "${red}No VMs with snapshots found.${reset}"
     main_menu
     return
   fi
 
   vm=$(printf "%s\n" "${vms_with_snapshots[@]}" | fzf --prompt="Select VM to delete snapshot from> " --height=40% --layout=reverse)
   if [ -z "$vm" ]; then
-    echo -e "${red}Action cancelled.${reset}"  # Correct color variable usage
+    echo -e "${red}Action cancelled.${reset}"
     main_menu
     return
   fi
@@ -232,8 +175,8 @@ delete_snapshot() {
     return
   fi
 
-  VBoxManage snapshot "$vm" delete "$snapshot_name" >/dev/null 2>&1  # Suppress command output
-  echo -e "${green}Snapshot '$snapshot_name' deleted from $vm.${reset}"  # Use color for success message
+  VBoxManage snapshot "$vm" delete "$snapshot_name" >/dev/null 2>&1
+  echo -e "${green}Snapshot '$snapshot_name' deleted from $vm.${reset}"
   main_menu
 }
 
